name: tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Download Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Get dependencies
      run: go get -v -t -d ./...
    
    - name: Build
      run: make build
      
    - name: Test
      run: make cover
      
    - name: Update coverage report
      if: github.event_name == 'push'
      uses: ncruces/go-coverage-report@v0
      with:
        coverage-file: coverage.out
        report: true
        chart: true
        amend: true
      continue-on-error: true
